### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by sandile11** [naclander/openmugen#1]
hi, how do you compile all the files at once, because when I use make all it gives the following error:

make all
make: *** No rule to make target 'all'.  Stop.
sandile@ubuntu:~/Desktop/openmugen$ make all

**Comment by naclander** [comment]
Hey @sandile11 

I cloned this repo a long time ago. I think the original source was able to compile on whatever version of windows it was originally created on, but I wouldn't be surpsirsed if it didn't compile on Windows anymore because of new changes.

As for Linux, when originaly  forking this repo I had intentions for getting it to compiile in Linux, but it's been on the backburner for a while now.

If you can write up a makefil that works and correctly compiles everything, that would be great, and I would be more than happy to accept a pull request.

**Comment by sandile11** [comment]
Hi, I managed to get it compile. I had to install dev-c++ for Windows. I couldn't write the makefile for Linux.

**Comment by MicahMartin** [comment]
What issues did you run into trying to compile this on linux? 
The Makefile.win looks like a good starting point, it's just a matter of converting these libs. 
Any info before I dive in?

**Comment by sandile11** [comment]
I think my mistake was trying to run the windows makefile in Linux. I also had no idea where to start with writing the makefile  for Linux considering how many files there are, and the order in which they should be compiled

**Comment by MicahMartin** [comment]
The windows makefile looks like a good place to start, it's just a matter of figuring out what the linux version of the windows dependencies are and correcting them in the makefile. then I think its a matter of changing any windows api calls / system api calls to their linux version? idk, gonna try

**Comment by sandile11** [comment]
Please submit a pull request if you do manage to do this. I think @naclander wouldn't mind. I'm sure you can get it done. you sound like you know your stuff.

**Comment by humbertodias** [comment]
@sandile11 cmake added [here](https://github.com/naclander/openmugen/pull/3) and now should work on linux as well

**Comment by naclander** [comment]
Fixed with #3
